#!/bin/bash
/home/sci/qwu/OSPRay/source/master/premake.sh  \
    --mpi --gcc \
    -o /ssd/users/qwu/ospray/build-vl3 \
    -i /ssd/users/qwu/ospray/install-vl3 \
    --gcc-exec "gcc" "g++" \
    --tbb-dir "/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb" \
    --embree-dir "/home/sci/qwu/software/embree-3.2.0.x86_64.linux" \
    --ispc-dir "/home/sci/qwu/software/ispc-v1.9.1-linux" \
    --icc-dir "" \
    --gcc-dir "/usr/bin" \
    --cmake-dir "cmake" \
    -a " -D Snappy_DIR=/home/sci/qwu/software/Lagodelcielo/snappy/install/lib64/cmake/Snappy " \
    -a " -D OSPRAY_BUILD_ISA=ALL" \
    -a " -D OSPRAY_MODULE_MPI=ON" \
    -a " -D OSPRAY_MODULE_MPI_APPS=ON" \
    -a " -D OSPRAY_SG_CHOMBO=OFF" \
    -a " -D OSPRAY_SG_VTK=OFF" \
    -a " -D OSPRAY_SG_OPENIMAGEIO=OFF" \
    -a " -D OSPRAY_APPS_EXAMPLEVIEWER=ON" \
    -a " -D OSPRAY_APPS_BENCHMARK=ON" \
    -a " -D OSPRAY_MODULE_PIDX=OFF" \
    -a " -D OSPRAY_MODULE_COSMICWEB=OFF" \
    -a " -D OSPRAY_MODULE_BRICKTREE=OFF" \
    -a " -D OSPRAY_MODULE_IMPLICIT_ISOSURFACES=OFF" \
    -a " -D OSPRAY_MODULE_TFN=OFF" \
    -a " -D OSPRAY_MODULE_TFN_WIDGET=OFF" \
    -a " -D OSPRAY_MODULE_SPLATTER=OFF" \
    -a " -D OSPRAY_MODULE_TUBES=OFF" \
    -a " -D OSPRAY_MODULE_VISIT=ON"  

