## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI Linux GPU Workflow

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

### BUILD JOBS ###

  build-ubuntu2204:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env
      level-zero-version: public/1.9.9
      submodules: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        scripts/build/linux.sh -G Ninja -DBUILD_GLFW=OFF -DBUILD_OSPRAY_MODULE_MULTIDEVICE=OFF -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON -DOPENVKL_URL=https://${RENDERKIT_GITHUB_TOKEN}@github.com/intel-innersource/libraries.graphics.renderkit.openvkl.git -DOPENVKL_BRANCH=gpu-devel -DRKCOMMON_VERSION=devel
      artifact-out: build-ubuntu2204
      artifact-path: build/install/ospray build/install/embree build/CMakeCache.txt build/*/build/CMakeCache.txt

  build-ubuntu2204-devel:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env
      level-zero-version: public/1.9.9
      submodules: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        scripts/build/linux.sh -G Ninja -DBUILD_GLFW=OFF -DBUILD_OSPRAY_MODULE_MULTIDEVICE=OFF -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON -DOPENVKL_URL=https://${RENDERKIT_GITHUB_TOKEN}@github.com/intel-innersource/libraries.graphics.renderkit.openvkl.git -DOPENVKL_BRANCH=gpu-devel -DRKCOMMON_VERSION=devel
      artifact-out: build-ubuntu2204-devel
      artifact-path: build/install/ospray build/install/embree build/CMakeCache.txt build/*/build/CMakeCache.txt

  build-ubuntu2204-mpi:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env
      level-zero-version: public/1.9.9
      submodules: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        scripts/build/linux.sh -G Ninja -DBUILD_GLFW=OFF -DBUILD_OSPRAY_MODULE_MPI=ON -DBUILD_OSPRAY_MODULE_MULTIDEVICE=OFF -DBUILD_GPU_SUPPORT=ON -DBUILD_OIDN=ON -DOPENVKL_URL=https://${RENDERKIT_GITHUB_TOKEN}@github.com/intel-innersource/libraries.graphics.renderkit.openvkl.git -DOPENVKL_BRANCH=gpu-devel -DRKCOMMON_VERSION=devel
      artifact-out: build-ubuntu2204-mpi
      artifact-path: build/install/ospray build/install/embree build/CMakeCache.txt build/*/build/CMakeCache.txt

  build-suse:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: opensuse/leap:15.3
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env
      level-zero-version: public/1.9.9
      submodules: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        scripts/build/linux.sh -DBUILD_GLFW=ON -DBUILD_OSPRAY_MODULE_MULTIDEVICE=OFF -DBUILD_GPU_SUPPORT=ON -DOPENVKL_URL=https://${RENDERKIT_GITHUB_TOKEN}@github.com/intel-innersource/libraries.graphics.renderkit.openvkl.git -DOPENVKL_BRANCH=gpu-devel -DRKCOMMON_VERSION=devel
      artifact-out: build-suse
      artifact-path: build/install/ospray build/install/embree build/CMakeCache.txt build/*/build/CMakeCache.txt


### TEST JOBS ###

  test-ubuntu2204-dg2:
    needs: [build-ubuntu2204]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env .github/workflows/gfx-ubuntu22.env
      submodules: true
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-ubuntu2204
      artifact-out: test-ubuntu2204-dg2
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/build/install/ospray/lib:$GITHUB_WORKSPACE/build/install/embree/lib:$LD_LIBRARY_PATH"
        export PATH="$GITHUB_WORKSPACE/build/install/ospray/bin:$PATH"
        scripts/tests/run_gpu_tests.sh "$GITHUB_WORKSPACE"

  test-ubuntu2204-pvc:
    needs: [build-ubuntu2204]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env .github/workflows/gfx-ubuntu22.env
      submodules: true
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "pvc" ]'
      artifact-in: build-ubuntu2204
      artifact-out: test-ubuntu2204-pvc
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/build/install/ospray/lib:$GITHUB_WORKSPACE/build/install/embree/lib:$LD_LIBRARY_PATH"
        export PATH="$GITHUB_WORKSPACE/build/install/ospray/bin:$PATH"
        scripts/tests/run_gpu_tests.sh "$GITHUB_WORKSPACE"

  test-ubuntu2204-devel-dg2:
    needs: [build-ubuntu2204-devel]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env .github/workflows/gfx-ubuntu22-internal.env
      submodules: true
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-ubuntu2204-devel
      artifact-out: test-ubuntu2204-devel-dg2
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true
      cmd: |
        export SYCL_BUNDLE_ROOT=$DPCPP_ROOT
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/build/install/ospray/lib:$GITHUB_WORKSPACE/build/install/embree/lib:$LD_LIBRARY_PATH"
        export PATH="$GITHUB_WORKSPACE/build/install/ospray/bin:$PATH"
        scripts/tests/run_gpu_tests.sh "$GITHUB_WORKSPACE"

  test-ubuntu2204-mpi:
    needs: build-ubuntu2204-mpi
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    secrets: inherit
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: ubuntu:22.04
      env-from-files: .github/workflows/dpcpp-sycl-nightly.env .github/workflows/gfx-ubuntu22-internal.env
      level-zero-version: public/1.9.9
      submodules: true
      options: --device=/dev/dri:/dev/dri
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-ubuntu2204-mpi
      artifact-out: test-ubuntu2204-mpi
      artifact-path: build_regression_tests/tests*.xml build_regression_tests/failed*
      artifact-on-failure: true
      cmd: |
        export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/build/install/ospray/lib:$GITHUB_WORKSPACE/build/install/embree/lib:$LD_LIBRARY_PATH"
        export PATH="$GITHUB_WORKSPACE/build/install/ospray/bin:$PATH"
        OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 scripts/tests/run_gpu_tests.sh "$GITHUB_WORKSPACE" TEST_MPI
